name: Build Luau

on:
  workflow_dispatch:

jobs:
  build-windows:
    uses: ./build-luau.windows.yaml
  build-linux:
    uses: ./build-luau.linux.yaml
  build-macOS:
    uses: ./build-luau.macOS.yaml
  build-iOS:
    uses: ./build-luau.ios.yaml
  build-android:
    uses: ./build-luau.android.yaml